# Tensorflow Matrix Math Exercises

In [5]:
import tensorflow as tf
import numpy as np

In [6]:
sess = tf.InteractiveSession()

NOTE on notation
* _x, _y, _z, ...: NumPy 0-d or 1-d arrays
* _X, _Y, _Z, ...: NumPy 2-d or higer dimensional arrays
* x, y, z, ...: 0-d or 1-d tensors
* X, Y, Z, ...: 2-d or higher dimensional tensors

## Matrix Math Functions

Q1. Create a diagonal tensor with the diagonal values of x.

In [12]:
_x = np.array([1, 2, 3, 4])
x = tf.convert_to_tensor(_x)
X = tf.diag(x)   
print(X.eval())

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


Q2. Extract the diagonal of X.

In [66]:
_X = np.array(
[[1, 0, 0, 0],
 [0, 2, 0, 0],
 [0, 0, 3, 0],
 [0, 0, 0, 4]])
X = tf.convert_to_tensor(_X)
#_y = np.array([[1, 1, 1, 1]])
#y = tf.convert_to_tensor(_y)
#y = tf.transpose(y)
#x = tf.matmul(X,y)
#x = tf.transpose(x)
x = tf.matrix_diag_part(X)
print(x.eval())

[1 2 3 4]


Q3. Permutate the dimensions of x such that the new tensor has shape (3, 4, 2).

In [62]:
_X = np.random.rand(2,3,4)
X = tf.convert_to_tensor(_X)
X = tf.transpose(X, perm=[1, 2, 0])
print(tf.dimension_value(X).shape)

(3, 4, 2)


Q4. Construct a 3 by 3 identity matrix.

In [72]:
_x = np.array([1., 1., 1.])
x = tf.convert_to_tensor(_x)
X = tf.diag(x)   
print(X.eval())

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Q5. Predict the result of this.

In [65]:
_X = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
X = tf.convert_to_tensor(_X)

diagonal_tensor = tf.matrix_diag(X)
diagonal_part = tf.matrix_diag_part(diagonal_tensor)

print("diagonal_tensor =\n", diagonal_tensor.eval())
print("diagonal_part =\n", diagonal_part.eval())


diagonal_tensor =
 [[[1 0 0 0]
  [0 2 0 0]
  [0 0 3 0]
  [0 0 0 4]]

 [[5 0 0 0]
  [0 6 0 0]
  [0 0 7 0]
  [0 0 0 8]]]
diagonal_part =
 [[1 2 3 4]
 [5 6 7 8]]


Q6. Transpose the last two dimensions of X.

In [69]:
_X= np.random.rand(1, 2, 3, 4)
X = tf.convert_to_tensor(_X)
X = tf.transpose(X, perm=[0,1,3,2])
print(tf.dimension_value(X).shape)

(1, 2, 4, 3)


Q7. Multiply X by Y.

In [70]:
_X = np.array([[1, 2, 3], [4, 5, 6]])
_Y = np.array([[1, 1], [2, 2], [3, 3]])
X = tf.convert_to_tensor(_X)
Y = tf.convert_to_tensor(_Y)
Z = tf.matmul(X,Y)
print(Z.eval())


[[14 14]
 [32 32]]


Q8. Multiply X and Y. The first axis represents batches.

In [8]:
_X = np.arange(1, 13, dtype=np.int32).reshape((2, 2, 3))
_Y = np.arange(13, 25, dtype=np.int32).reshape((2, 3, 2))
X = tf.convert_to_tensor(_X)
Y = tf.convert_to_tensor(_Y)
Z = tf.matmul(X, Y)
print(Z.eval())

[[[ 94 100]
  [229 244]]

 [[508 532]
  [697 730]]]


Q9. Compute the determinant of X.

In [89]:
_X = np.arange(1, 5, dtype=np.float32).reshape((2, 2))
X = tf.convert_to_tensor(_X)
z = tf.matrix_determinant(X)
print(z.eval())


-2.0


Q10. Compute the inverse of X.


In [7]:
_X = np.arange(1, 5, dtype=np.float64).reshape((2, 2))
X = tf.convert_to_tensor(_X)
X = tf.matrix_inverse(X)
print(X.eval())

[[-2.   1. ]
 [ 1.5 -0.5]]
